import type { EngineLine } from "@/lib/chess/types";
import data from "./sample-data.json";

/**
 * A real public chess.com game (PGN + usernames only), regenerated by
 * `pnpm tsx scripts/precompute-sample.ts --lines`.
 */
export const SAMPLE_GAME: {
  id: string;
  url: string;
  pgn: string;
  white: string;
  black: string;
  whiteElo: number | null;
  blackElo: number | null;
  timeClass: string;
  note: string;
} = {
  id: data.id,
  url: data.url,
  pgn: data.pgn,
  white: data.white,
  black: data.black,
  whiteElo: data.whiteElo,
  blackElo: data.blackElo,
  timeClass: data.timeClass,
  note: data.note,
};

/** Stockfish 19 lite at depth 16; index i = position before ply i, plus one for the final position. */
export const SAMPLE_LINES: EngineLine[] = data.lines as EngineLine[];

export const SAMPLE_ENGINE = { name: data.engine, depth: data.depth };
